#mysql和阿里druid配置
spring:
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.informix.jdbc.IfxDriver
    url: jdbc:informix-sqli://172.16.105.51:9088/gzzwgx:informixserver=gbaseserver;DB_LOCALE=zh_cn.utf8;DBDATE=Y4MD;GL_DATE="%m/%d/%iY";GL_DATETIME="%iY-%m-%d %H:%M:%S";DELIMIDENT=n
    username: informix
    password: informix
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
#    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#    filters: log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
#    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
#去除浏览器小图标
  mvc:
    favicon:
      enabled: false
# mybatis配置
mybatis: 
  mapper-locations: classpath*:/mapper/*Mapper.xml
  configLocation: classpath:/mybatis-config.xml
# Server port
server:
  port: 7000
  #contextPath: /

